services:
  app:
    image: ghcr.io/stac-utils/stac-fastapi-pgstac:main
    restart: unless-stopped
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - STAC FASTAPI_TITLE=AGH
      - STAC FASTAPI_DESCRIPTION=AGH
      - STAC_FASTAPI_LANDING_ID=AGH
      - STAC_FASTAPI_VERSION=AGH
      - USE_API_HYDRATE=true

    depends_on:
      - database
    command: bash -c "./scripts/wait-for-it.sh database:5432 && python -m stac_fastapi.pgstac.app"

  database:
    image: ghcr.io/stac-utils/pgstac:v0.9.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  browser:
    image: ghcr.io/radiantearth/stac-browser:latest
    environment:
      - SB_catalogUrl=http://localhost:8082/
      - SB_catalogTitle="My First Stac"

  eometadatatool:
    image: ghcr.io/mathewnwsh/eometadatatool:1bfe0af
#   caddy:
#     image: caddy:2
#     restart: unless-stopped
#     cap_add:
#       - NET_ADMIN
#     depends_on:
#       - app
#       - browser
#     ports:
#       - "80:80"
#       - "443:443"
#       - "443:443/udp"
#     configs:
#       - source: caddyfile
#         target: /etc/caddy/Caddyfile
#     volumes:
#       - ./caddy_data:/data
#       - ./caddy_config:/config

# configs:
#   caddyfile:
#     content: |
#       stac.bosnia.marcys.dev {
#           reverse_proxy app:8082
#       }

#       browser.bosnia.marcys.dev {
#           reverse_proxy browser:8080
